import { Inter } from "next/font/google";
import type { Metadata } from "next";

export const inters=Inter({ subsets: ["latin"] });
export const metadatas = {
  title: "Login page",
  description: "Generated by create next app",
};