import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
// import {Logouts} from '../Components/Logout'
import Logs from '../Components/Log'
import Link from "next/link";
import RouteAthu from "@/Components/RouteAthu";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Login page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RouteAthu/>
        <div className="container-fluid">
<header className="row">
  <div className="col-12">
<nav className="navbar navbar-expand-lg">
  <div className="container">
    <Link className="navbar-brand" href="/">Todo List</Link>
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarNav">
      <ul className="navbar-nav ms-auto me-4 d-flex align-items-center">
        <li className="nav-item">
          <Link className="nav-link" href="/Register">Register</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" href="/Login">Login</Link>
        </li>
        {/* <li className="nav-item">
          <Link className="nav-link" href="/Dashboard">Dashboard</Link>
        </li> */}
        <li className="nav-item">
{/* <Logouts/> */}
<Logs/>
        </li>
      </ul>
    </div>
  </div>
</nav>
  </div>
  
</header>
        {children}
        </div>
        </body>
    </html>
  );
}
